uint8 OP_SET=0
uint8 OP_RELEASE=1

string owner
string mission_id
string transaction_id
string lease_id
builtin_interfaces/Duration lease_duration
bool recovery
uint8 operation
---
uint8 RESULT_OK=0
uint8 RESULT_INVALID_REQUEST=1
uint8 RESULT_CONFLICT=2
uint8 RESULT_NOT_OWNER=3
uint8 RESULT_STALE_LEASE=4

bool success
uint8 result_code
string message
robot_interfaces/MotionInterlockState state
