#!/usr/bin/env bash

# One ownership inventory is shared by the in-container cleanup and the host
# systemd runner's post-cleanup proof. Keep wrappers and their server processes
# together so a new runtime owner cannot be added to only one side.
NJRH_RUNTIME_COMMON_PATTERN="run_common_services[.]sh"
NJRH_RUNTIME_NODE_PATTERN="run_driver[.]sh|run_pointcloud_accel_pipeline[.]sh|laser_scan_to_flatscan|hesai_ros_driver_node|pointcloud_accel_axis_node|pointcloud_axis_remap|imu_axis_remap|ranger_base_node|robot_description_static_tf_node|robot_eai_gs2/gs2_driver_node|gs2_driver_node --ros-args|ros2 launch robot_eai_gs2 gs2[.]launch[.]py|run_orbbec_336l_depth[.]sh|orbbec_camera|camera336l|run_orbbec_docking_perception[.]sh|orbbec_depth_dock_node|runtime_health_guard[.]py|run_runtime_health_guard[.]sh|run_floor_manager[.]sh|stop_floor_navigation[.]sh|robot_floor_manager/floor_manager_node|floor_manager_node --ros-args|run_robot_safety[.]sh|robot_safety/robot_safety_node|robot_safety_node --ros-args|run_mode_manager[.]sh|robot_mode_manager/mode_manager_node|mode_manager_node --ros-args|run_docking_manager[.]sh|robot_docking_manager/docking_manager_node|docking_manager_node --ros-args|ekf_node --ros-args.*__node:=robot_local_state|robot_localization/ekf_node|robot_local_perception/local_perception_node|ranger_mini3_mode_controller/mode_controller_node|run_robot_api_server[.]sh|run_robot_api_server_supervised[.]sh|robot_api_server/robot_api_server_node|/install/robot_api_server/lib/robot_api_server/robot_api_server_node|robot_api_server_node --ros-args|run_projected_map[.]sh|run_jt128_2d_mapping[.]sh|jt128_slam_toolbox_mapping[.]launch[.]py|jt128_2d_mapping[.]launch[.]py|slam_toolbox|mapping_scan_tf_gate_node|fastlio_mapping_odom_bridge[.]py|/mapping/fastlio_odometry|/tf_slam2d|ros2 run fast_lio fastlio_mapping|fast_lio/lib/fast_lio/fastlio_mapping|fastlio_mapping --ros-args|run_navigation_runtime_services[.]sh|nav2_lifecycle_sequence[.]py|call_global_localization_trigger[.]py|run_nav2_navigation[.]sh|run_occupancy_grid_localization[.]sh|standard_navigation[.]launch[.]py|occupancy_localization_stack[.]launch[.]py|occupancy_grid_localizer_container|occupancy_grid_localizer|robot_global_localization/global_localization_node|/install/robot_global_localization/lib/robot_global_localization/global_localization_node|robot_localization_bridge/localization_bridge_node|localization_bridge_node --ros-args|amcl --ros-args|nav2_amcl|amcl_scan_admission|__node:=map_server|__node:=controller_server|__node:=planner_server|__node:=bt_navigator|__node:=behavior_server|__node:=velocity_smoother|__node:=collision_monitor|__node:=lifecycle_manager_navigation|__node:=lifecycle_manager_costmap_filters"
# These process owners can survive after their launch parent exits. Match the
# executable path or the exact ROS node remap with a trailing argv boundary;
# broad tokens such as "component_container_mt" would also catch unrelated
# localization/component containers.
NJRH_RUNTIME_POINTCLOUD_NODE_PATTERN="/pointcloud_perception_pipeline[.]launch[.]py([[:space:]]|$)|/component_container_mt([[:space:]]|$).*__node:=pointcloud_perception_pipeline([[:space:]]|$)|/hesai_accel_driver_node([[:space:]]|$)|/jt128_accel_driver_node([[:space:]]|$)|/pointcloud_downsample_node([[:space:]]|$)|/pointcloud_fastlio_remap([[:space:]]|$)|__node:=pointcloud_fastlio_remap([[:space:]]|$)"
NJRH_RUNTIME_NAV2_NODE_PATTERN="/smoother_server([[:space:]]|$)|__node:=smoother_server([[:space:]]|$)|/waypoint_follower([[:space:]]|$)|__node:=waypoint_follower([[:space:]]|$)"
NJRH_RUNTIME_NODE_PATTERN="${NJRH_RUNTIME_NODE_PATTERN}|${NJRH_RUNTIME_POINTCLOUD_NODE_PATTERN}|${NJRH_RUNTIME_NAV2_NODE_PATTERN}"
NJRH_RUNTIME_ROS2_CLI_PATTERN="/opt/ros/humble/bin/ros2 (lifecycle (get|set)|topic (echo|hz|info|pub)|node info|service call|action send_goal)|ros2 (lifecycle (get|set)|topic (echo|hz|info|pub)|node info|service call|action send_goal)"
NJRH_RUNTIME_ALL_PATTERN="${NJRH_RUNTIME_COMMON_PATTERN}|${NJRH_RUNTIME_NODE_PATTERN}|${NJRH_RUNTIME_ROS2_CLI_PATTERN}"
