schema_version: 3
mock_ports_enabled: false

building_id: building_1
elevators:
  - elevator_id: elevator_west
    floors:
      - floor_id: F1
        map_id: map_f1_release
        hall_call_panel_side: LEFT
        cabin_panel_side: RIGHT
        poses:
          hall_call: f1_west_hall_call
          landing: f1_west_landing
          cabin: f1_west_cabin
          cabin_panel: f1_west_cabin_panel
      - floor_id: F2
        map_id: map_f2_release
        hall_call_panel_side: RIGHT
        cabin_panel_side: LEFT
        poses:
          hall_call: f2_west_hall_call
          landing: f2_west_landing
          cabin: f2_west_cabin
          cabin_panel: f2_west_cabin_panel
