#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


def ensure_floor_assets(root: Path, building_id: str, floor_id: str) -> None:
    floor_root = root / building_id / floor_id
    for rel in (
        "nav/nav_map.yaml",
        "nav/nav_map.pgm",
        "localizer/localizer_map.png",
        "localizer/localizer_params.yaml",
        "filters/keepout_mask.yaml",
        "filters/keepout_mask.pgm",
        "filters/speed_mask.yaml",
        "filters/speed_mask.pgm",
        "filters/binary_mask.yaml",
        "filters/binary_mask.pgm",
        "reports/asset_report.json",
        "poses.yaml",
    ):
        path = floor_root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists():
            path.write_text("# generated by robot_map_toolkit skeleton\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--maps-root", type=Path, default=Path("maps"))
    parser.add_argument("--building-id", default="building_1")
    parser.add_argument("--floor-id", default="floor_1")
    args = parser.parse_args()
    ensure_floor_assets(args.maps_root, args.building_id, args.floor_id)
    print(args.maps_root / args.building_id / args.floor_id)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
