#include "robot_api_server/docking_job_model.hpp"

#include <iomanip>
#include <sstream>

#include "robot_api_server/http_common.hpp"

namespace robot_api_server
{

std::string docking_job_json(const DockingJob & job)
{
  std::ostringstream response;
  response << std::fixed << std::setprecision(6);
  response << "{\"id\":" << job.id << ","
           << "\"state\":" << json_string(job.state) << ","
           << "\"phase\":" << json_string(job.phase) << ","
           << "\"building_id\":" << json_string(job.building_id) << ","
           << "\"floor_id\":" << json_string(job.floor_id) << ","
           << "\"map_id\":" << json_string(job.map_id) << ","
           << "\"dock_id\":" << json_string(job.dock_id) << ","
           << "\"dock_name\":" << json_string(job.dock_name) << ","
           << "\"dock_type\":" << json_string(job.dock_type) << ","
           << "\"dock_profile_id\":" << json_string(job.dock_profile_id) << ","
           << "\"dock_profile_type\":" << json_string(job.dock_profile_type) << ","
           << "\"approach_direction\":" << json_string(job.approach_direction) << ","
           << "\"contact_frame\":" << json_string(job.contact_frame) << ","
           << "\"sensor_frame\":" << json_string(job.sensor_frame) << ","
           << "\"goal_completion_policy\":" << json_string(job.goal_completion_policy) << ","
           << "\"predock_pose_id\":" << json_string(job.predock_pose_id) << ","
           << "\"approach_source\":" << json_string(job.approach_source) << ","
           << "\"failure_code\":" << json_string(job.failure_code) << ","
           << "\"last_error_code\":" << json_string(job.last_error_code) << ","
           << "\"last_error_detail\":" << json_string(job.last_error_detail) << ","
           << "\"max_retries\":" << job.max_retries << ","
           << "\"retry_count\":" << job.retry_count << ","
           << "\"ok\":" << (job.ok ? "true" : "false") << ","
           << "\"resume_navigation\":" << (job.resume_navigation ? "true" : "false") << ","
           << "\"nav_goal_sent\":" << (job.nav_goal_sent ? "true" : "false") << ","
           << "\"nav_goal_succeeded\":" << (job.nav_goal_succeeded ? "true" : "false") << ","
           << "\"dock_staging_handoff_ready\":"
           << (job.dock_staging_handoff_ready ? "true" : "false") << ","
           << "\"predock_pose_verified\":" << (job.predock_pose_verified ? "true" : "false") << ","
           << "\"predock_xy_ok\":" << (job.predock_xy_ok ? "true" : "false") << ","
           << "\"predock_base_yaw_ok\":" << (job.predock_base_yaw_ok ? "true" : "false") << ","
           << "\"predock_contact_yaw_ok\":" << (job.predock_contact_yaw_ok ? "true" : "false") << ","
           << "\"predock_yaw_align_attempted\":"
           << (job.predock_yaw_align_attempted ? "true" : "false") << ","
           << "\"predock_yaw_aligned\":" << (job.predock_yaw_aligned ? "true" : "false") << ","
           << "\"predock_yaw_align_succeeded\":"
           << (job.predock_yaw_align_succeeded ? "true" : "false") << ","
           << "\"predock_yaw_align_required_actual_spin\":"
           << (job.predock_yaw_align_required_actual_spin ? "true" : "false") << ","
           << "\"predock_distance_m\":" << job.predock_distance_m << ","
           << "\"predock_expected_base_yaw\":" << job.predock_expected_base_yaw << ","
           << "\"predock_expected_contact_yaw\":" << job.predock_expected_contact_yaw << ","
           << "\"predock_current_base_yaw\":" << job.predock_current_base_yaw << ","
           << "\"predock_current_contact_yaw\":" << job.predock_current_contact_yaw << ","
           << "\"predock_base_yaw_error_rad\":" << job.predock_base_yaw_error_rad << ","
           << "\"predock_contact_yaw_error_rad\":" << job.predock_contact_yaw_error_rad << ","
           << "\"predock_yaw_align_initial_error_rad\":" << job.predock_yaw_align_initial_error_rad << ","
           << "\"predock_yaw_align_final_error_rad\":" << job.predock_yaw_align_final_error_rad << ","
           << "\"predock_yaw_align_duration_sec\":" << job.predock_yaw_align_duration_sec << ","
           << "\"predock_yaw_align_observed_yaw_motion_rad\":"
           << job.predock_yaw_align_observed_yaw_motion_rad << ","
           << "\"predock_yaw_align_detail\":" << json_string(job.predock_yaw_align_detail) << ","
           << "\"predock_yaw_align_failure_code\":"
           << json_string(job.predock_yaw_align_failure_code) << ","
           << "\"fine_entry_checked\":" << (job.fine_entry_checked ? "true" : "false") << ","
           << "\"fine_entry_ok\":" << (job.fine_entry_ok ? "true" : "false") << ","
           << "\"fine_entry_distance_m\":" << job.fine_entry_distance_m << ","
           << "\"fine_entry_base_yaw_error_rad\":" << job.fine_entry_base_yaw_error_rad << ","
           << "\"fine_entry_contact_yaw_error_rad\":" << job.fine_entry_contact_yaw_error_rad << ","
           << "\"fine_entry_failure_code\":" << json_string(job.fine_entry_failure_code) << ","
           << "\"fine_entry_detail\":" << json_string(job.fine_entry_detail) << ","
           << "\"global_correction_paused\":" << (job.global_correction_paused ? "true" : "false") << ","
           << "\"pause_reason\":" << json_string(job.pause_reason) << ","
           << "\"post_predock_settle_complete\":"
           << (job.post_predock_settle_complete ? "true" : "false") << ","
           << "\"ordinary_final_yaw_align_active\":"
           << (job.ordinary_final_yaw_align_active ? "true" : "false") << ","
           << "\"predock_yaw_align_active\":"
           << (job.predock_yaw_align_active ? "true" : "false") << ","
           << "\"cmd_owner_conflict_detected\":"
           << (job.cmd_owner_conflict_detected ? "true" : "false") << ","
           << "\"final_yaw_align_blocked_by_docking\":"
           << (job.final_yaw_align_blocked_by_docking ? "true" : "false") << ","
           << "\"docking_blocked_by_final_yaw_align\":"
           << (job.docking_blocked_by_final_yaw_align ? "true" : "false") << ","
           << "\"display_pose_source\":" << json_string(job.display_pose_source) << ","
           << "\"display_pose\":{\"x\":" << job.display_pose_x
           << ",\"y\":" << job.display_pose_y
           << ",\"yaw\":" << job.display_pose_yaw
           << ",\"age_sec\":" << job.display_pose_age_sec << "},"
           << "\"relocalization_requested\":" << (job.relocalization_requested ? "true" : "false") << ","
           << "\"relocalization_succeeded\":" << (job.relocalization_succeeded ? "true" : "false") << ","
           << "\"relocalization_detail\":" << json_string(job.relocalization_detail) << ","
           << "\"post_predock_relocalization_requested\":"
           << (job.post_predock_relocalization_requested ? "true" : "false") << ","
           << "\"post_predock_relocalization_succeeded\":"
           << (job.post_predock_relocalization_succeeded ? "true" : "false") << ","
           << "\"post_predock_relocalization_required\":"
           << (job.post_predock_relocalization_required ? "true" : "false") << ","
           << "\"post_predock_relocalization_detail\":"
           << json_string(job.post_predock_relocalization_detail) << ","
           << "\"post_fine_docking_relocalization_requested\":"
           << (job.post_fine_docking_relocalization_requested ? "true" : "false") << ","
           << "\"post_fine_docking_relocalization_succeeded\":"
           << (job.post_fine_docking_relocalization_succeeded ? "true" : "false") << ","
           << "\"post_fine_docking_relocalization_required\":"
           << (job.post_fine_docking_relocalization_required ? "true" : "false") << ","
           << "\"post_fine_docking_relocalization_detail\":"
           << json_string(job.post_fine_docking_relocalization_detail) << ","
           << "\"post_undock_relocalization_requested\":"
           << (job.post_undock_relocalization_requested ? "true" : "false") << ","
           << "\"post_undock_relocalization_succeeded\":"
           << (job.post_undock_relocalization_succeeded ? "true" : "false") << ","
           << "\"post_undock_relocalization_required\":"
           << (job.post_undock_relocalization_required ? "true" : "false") << ","
           << "\"post_undock_relocalization_detail\":"
           << json_string(job.post_undock_relocalization_detail) << ","
           << "\"post_undock_relocalization_started\":"
           << (job.post_undock_relocalization_started ? "true" : "false") << ","
           << "\"post_undock_relocalization_accepted\":"
           << (job.post_undock_relocalization_accepted ? "true" : "false") << ","
           << "\"post_undock_settle_started\":"
           << (job.post_undock_settle_started ? "true" : "false") << ","
           << "\"post_undock_settle_complete\":"
           << (job.post_undock_settle_complete ? "true" : "false") << ","
           << "\"post_undock_settle_failure_reason\":"
           << json_string(job.post_undock_settle_failure_reason) << ","
           << "\"pending_goal_held_for_post_undock_settle\":"
           << (job.pending_goal_held_for_post_undock_settle ? "true" : "false") << ","
           << "\"pending_goal_released_after_post_undock_settle\":"
           << (job.pending_goal_released_after_post_undock_settle ? "true" : "false") << ","
           << "\"using_triggered_baseline_only\":"
           << (job.using_triggered_baseline_only ? "true" : "false") << ","
           << "\"amcl_ready\":" << (job.amcl_ready ? "true" : "false") << ","
           << "\"localization_degraded\":"
           << (job.localization_degraded ? "true" : "false") << ","
           << "\"active_navigation_cancel_requested\":"
           << (job.active_navigation_cancel_requested ? "true" : "false") << ","
           << "\"active_navigation_cancel_detail\":" << json_string(job.active_navigation_cancel_detail) << ","
           << "\"api_accepted\":" << (job.api_accepted ? "true" : "false") << ","
           << "\"already_running\":" << (job.already_running ? "true" : "false") << ","
           << "\"docking_service_called\":" << (job.docking_service_called ? "true" : "false") << ","
           << "\"docking_service_success\":" << (job.docking_service_success ? "true" : "false") << ","
           << "\"docking_service_message\":" << json_string(job.docking_service_message) << ","
           << "\"docking_status_at_request\":" << json_string(job.docking_status_at_request) << ","
           << "\"docking_status_after_request\":" << json_string(job.docking_status_after_request) << ","
           << "\"undock_started_observed\":" << (job.undock_started_observed ? "true" : "false") << ","
           << "\"undock_cmd_count_observed\":" << job.undock_cmd_count_observed << ","
           << "\"undock_failure_reason\":" << json_string(job.undock_failure_reason) << ","
           << "\"docking_service_warning\":" << json_string(job.docking_service_warning) << ","
           << "\"cancel_requested\":" << (job.cancel_requested ? "true" : "false") << ","
           << "\"dock_pose\":{\"x\":" << job.dock_x << ",\"y\":" << job.dock_y
           << ",\"yaw\":" << job.dock_yaw << "},"
           << "\"approach_pose\":{\"x\":" << job.approach_x << ",\"y\":" << job.approach_y
           << ",\"yaw\":" << job.approach_yaw << "},"
           << "\"approach_distance_m\":" << job.approach_distance_m << ","
           << "\"detail\":" << json_string(job.detail) << ","
           << "\"last_status\":" << json_string(job.last_status) << ","
           << "\"started_at\":" << json_string(job.started_at) << ","
           << "\"finished_at\":" << json_string(job.finished_at) << "}";
  return response.str();
}

}  // namespace robot_api_server
