pointcloud_axis_remap:
  ros__parameters:
    input_topic: /jt128/vendor/points_raw
    output_topic: /lidar_points
    output_frame_id: lidar_link
    rotation_matrix:
      - 0.0
      - 1.0
      - 0.0
      - -1.0
      - 0.0
      - 0.0
      - 0.0
      - 0.0
      - 1.0
